
import {Button, HorizontalBox, VerticalBox} from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 800px;
    height: 600px;
    background: black;
    title: "PhiWOW - 这是什么a";
    VerticalBox {
        spacing: 100px;
        Image {
            source: @image-url("assets/Pause.png");
            width: 30px;
            height: 30px;
            padding: 100px;
        }
        Image {
            source: @image-url("assets/line.png");
        }

    }
    
}